- name: Verify Contract
        env:
          RH_RPC_URL: https://rpc.testnet.chain.robinhood.com
        run: |
          forge verify-contract 0xc1A320cc30d9D7358096d1f1D32162680978Eb48 \
            src/HelloRobinhood.sol:HelloRobinhood \
            --chain-id 46630 \
            --rpc-url $RH_RPC_URL \
            --verifier blockscout \
            --verifier-url https://explorer.testnet.chain.robinhood.com/api/
