name: Swap
on:
  workflow_dispatch:

jobs:
  run-swap:
    runs-on: ubuntu-latest
    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Exec
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          cast send 0xa342734ca2980b3d98a16ea3a052736e611a6760 \
            "executeSwap(address,address,uint256,uint256)" \
            0xC9f9c86933092BbbfFF3CCb4b105A4A94bf3Bd4E \
            0xBA72e7572b3cAb2C5bDDD082717684B3551a7A64 \
            10000000000000000000 0 \
            --rpc-url https://rpc.testnet.chain.robinhood.com/ \
            --private-key $PRIVATE_KEY
